name: Heroku deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get config.yaml gist
      id: get
      uses: andymckay/get-gist-action@master
      with:
        gistURL: ${{secrets.CONFIG_GIST}}
    - name: Move config.yaml to repo
      id: run
      run: |
        cp ${{ steps.get.outputs.file }} .
    - name: Build and deploy docker to Heroku
      uses: akhileshns/heroku-deploy@v3.0.5
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
        docker_heroku_process_type: "worker"
