name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Gist
      id: get
      uses: andymckay/get-gist-action@master
      with:
        gistURL: "https://gist.github.com/saanuregh/3609c7cee8916eaf3348d7a35a3cdeb0" 
    - name: Show Gist contents
      id: run
      run: |
        cat ${{ steps.get.outputs.file }} && ls
